name: Build docs manually
on:
  workflow_dispatch

jobs:
  build_sphinx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'
      
      - name: Install sphinx
        run: |
          python -m pip -r requirements.txt
      
      - name: Build docs
        run: |
          make html
          
      - uses: actions/upload-artifact@v2
        with:
          name: pyemir-tutorials-docs
          path: build/html
