name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false

jobs:
  build_sphinx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'
      
      - name: Install sphinx
        run: |
          python -m pip install sphinx
      
      - name: Build docs
        run: |
          make html
          
      - uses: actions/upload-artifact@v2
        with:
          name: pyemir-tutorials-docs
          path: build/html
